<a href="https://colab.research.google.com/github/GhaziFadhlullah/DIF62130_B-_25_2311532012/blob/main/Praktikum4/GaussianNB.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
import pandas as pd
import numpy as np

Kode ini berisi perintah untuk mengimpor beberapa library dan fungsi yang sering digunakan dalam pemodelan machine learning.

train_test_split dari sklearn.model_selection digunakan untuk membagi dataset menjadi data latih dan data uji secara acak agar model bisa dilatih dan diuji secara terpisah.

accuracy_score dari sklearn.metrics dipakai untuk mengukur performa model dengan menghitung persentase prediksi yang benar.

pandas diimpor dengan alias pd untuk mengelola dan memanipulasi data dalam bentuk tabel (dataframe).

numpy diimpor dengan alias np untuk melakukan operasi numerik dan komputasi matematis yang efisien.

Import ini biasanya menjadi langkah awal dalam membuat program machine learning agar semua alat yang diperlukan sudah siap digunakan.











In [2]:
dataset_dict = {
    'Rainfall': [0.0, 2.0, 7.0, 18.0, 3.0, 3.0, 0.0, 1.0, 0.0, 25.0, 0.0, 18.0, 9.0, 5.0, 0.0, 1.0, 7.0, 0.0, 0.0, 7.0, 5.0, 3.0, 0.0, 2.0, 0.0, 8.0, 4.0, 4.0],
    'Temperature': [29.4, 26.7, 28.3, 21.1, 20.0, 18.3, 17.8, 22.2, 20.6, 23.9, 23.9, 22.2, 27.2, 21.7, 27.2, 23.3, 24.4, 25.6, 27.8, 19.4, 29.4, 22.8, 31.1, 25.0, 26.1, 26.7, 18.9, 28.9],
    'Humidity': [85.0, 90.0, 78.0, 96.0, 80.0, 70.0, 65.0, 95.0, 70.0, 80.0, 70.0, 90.0, 75.0, 80.0, 88.0, 92.0, 85.0, 75.0, 92.0, 90.0, 85.0, 88.0, 65.0, 70.0, 60.0, 95.0, 70.0, 78.0],
    'WindSpeed': [2.1, 21.2, 1.5, 3.3, 2.0, 17.4, 14.9, 6.9, 2.7, 1.6, 30.3, 10.9, 3.0, 7.5, 10.3, 3.0, 3.9, 21.9, 2.6, 17.3, 9.6, 1.9, 16.0, 4.6, 3.2, 8.3, 3.2, 2.2],
    'Play': ['No', 'No', 'Yes', 'Yes', 'Yes', 'No', 'Yes', 'No', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'No', 'No', 'Yes', 'Yes', 'No', 'No', 'No', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'No', 'Yes']
}

df = pd.DataFrame(dataset_dict)
df.head()

Rainfall  Temperature  Humidity  WindSpeed Play
0       0.0         29.4      85.0        2.1   No
1       2.0         26.7      90.0       21.2   No
2       7.0         28.3      78.0        1.5  Yes
3      18.0         21.1      96.0        3.3  Yes
4       3.0         20.0      80.0        2.0  Yes

Kode ini membuat sebuah dataset sederhana dalam bentuk dictionary yang berisi data cuaca dan keputusan bermain. Dataset ini memiliki lima kolom yaitu Rainfall (curah hujan), Temperature (suhu), Humidity (kelembapan), WindSpeed (kecepatan angin), dan Play (keputusan bermain, dengan nilai "Yes" atau "No").

Selanjutnya, dictionary tersebut dikonversi menjadi sebuah DataFrame menggunakan pd.DataFrame(). DataFrame ini adalah struktur data tabular yang mudah digunakan untuk analisis dan pemrosesan data dalam Python.

Terakhir, df.head() menampilkan lima baris pertama dari DataFrame untuk memberikan gambaran awal tentang isi dataset tersebut. Ini membantu melihat seperti apa data yang akan diproses dan dianalisis.

Bagi data menjadi data latih dan data uji





In [3]:
X, y = df.drop(columns='Play'), df['Play']

X_train, X_test, y_train, y_test = train_test_split(X, y, train_size=0.7, shuffle=False)
print(pd.concat([X_train, y_train], axis=1), end='\n\n')
print(pd.concat([X_test, y_test], axis=1))

    Rainfall  Temperature  Humidity  WindSpeed Play
0        0.0         29.4      85.0        2.1   No
1        2.0         26.7      90.0       21.2   No
2        7.0         28.3      78.0        1.5  Yes
3       18.0         21.1      96.0        3.3  Yes
4        3.0         20.0      80.0        2.0  Yes
5        3.0         18.3      70.0       17.4   No
6        0.0         17.8      65.0       14.9  Yes
7        1.0         22.2      95.0        6.9   No
8        0.0         20.6      70.0        2.7  Yes
9       25.0         23.9      80.0        1.6  Yes
10       0.0         23.9      70.0       30.3  Yes
11      18.0         22.2      90.0       10.9  Yes
12       9.0         27.2      75.0        3.0  Yes
13       5.0         21.7      80.0        7.5   No
14       0.0         27.2      88.0       10.3   No
15       1.0         23.3      92.0        3.0  Yes
16       7.0         24.4      85.0        3.9  Yes
17       0.0         25.6      75.0       21.9   No
18       0.0

Kode ini memisahkan dataset menjadi dua bagian, yaitu fitur dan target. Variabel X berisi semua kolom kecuali kolom Play, yang merupakan fitur atau data input, sementara y berisi kolom Play yang menjadi target atau label yang ingin diprediksi.

Selanjutnya, data dibagi menjadi data latih dan data uji menggunakan fungsi train_test_split. Dengan parameter train_size=0.7, 70% data digunakan untuk pelatihan, dan sisanya 30% untuk pengujian. Parameter shuffle=False memastikan data tidak diacak saat pembagian, sehingga urutan data tetap terjaga.

Terakhir, dua bagian data tersebut, baik data latih dan data uji, digabungkan kembali dengan label masing-masing menggunakan pd.concat agar dapat ditampilkan secara lengkap. Fungsi print menampilkan data latih dan data uji tersebut secara berurutan dengan jarak baris kosong di antaranya, sehingga mudah untuk melihat bagaimana data dibagi dan apa saja isi dari masing-masing bagian.

Transforming non-Gaussian distributed data

In [4]:
from sklearn.preprocessing import PowerTransformer

pt = PowerTransformer(standardize=True)
X_train_transformed = pt.fit_transform(X_train)
X_test_transformed = pt.transform(X_test)
print(X_train_transformed)

[[-1.12664679  1.70170305  0.31329077 -1.06372102]
 [ 0.05597219  0.87952169  0.88230332  1.34533274]
 [ 0.86716996  1.36597555 -0.45277799 -1.45338193]
 [ 1.43333755 -0.80381552  1.58840659 -0.52887309]
 [ 0.31508602 -1.13057488 -0.23760221 -1.12107835]
 [ 0.31508602 -1.63274871 -1.28303046  1.18531636]
 [-1.12664679 -1.77976256 -1.77644441  1.05270656]
 [-0.3427653  -0.47570144  1.46898652  0.30465822]
 [-1.12664679 -0.9525142  -1.28303046 -0.76627067]
 [ 1.6099061   0.03391302 -0.23760221 -1.37993965]
 [-1.12664679  0.03391302 -1.28303046  1.61012798]
 [ 1.43333755 -0.47570144  0.88230332  0.76671735]
 [ 1.02527709  1.03129394 -0.76988727 -0.64142374]
 [ 0.64971568 -0.62500825 -0.23760221  0.39259042]
 [-1.12664679  1.03129394  0.6525535   0.71225976]
 [-0.3427653  -0.14629167  1.11488006 -0.64142374]
 [ 0.86716996  0.18435986  0.31329077 -0.33327305]
 [-1.12664679  0.54642886 -0.76988727  1.37070938]
 [-1.12664679  1.21371571  1.11488006 -0.81103354]]


Kode ini digunakan untuk melakukan transformasi data fitur menggunakan teknik Power Transformer, yang berfungsi untuk membuat distribusi data menjadi lebih mendekati distribusi normal.

Pertama, objek PowerTransformer dibuat dengan parameter standardize=True, artinya setelah transformasi, data juga akan dinormalisasi menjadi memiliki rata-rata nol dan standar deviasi satu.

Kemudian, fit_transform diaplikasikan pada data pelatihan X_train untuk mempelajari parameter transformasi dari data tersebut sekaligus menerapkannya, sehingga menghasilkan data X_train_transformed yang sudah ditransformasi.

Selanjutnya, transform digunakan pada data uji X_test dengan parameter transformasi yang sama seperti pada data latih, menghasilkan X_test_transformed. Ini memastikan bahwa data uji diproses dengan cara yang konsisten.

Terakhir, hasil transformasi data pelatihan dicetak agar bisa dilihat bagaimana data asli berubah setelah transformasi ini dilakukan. Transformasi ini membantu meningkatkan performa model dengan membuat data lebih sesuai untuk algoritma machine learning yang digunakan.











TRAINING STEPS

1.class probability calculation

In [5]:


# Calculate prior probabilities for each class
prior_probabilities = y_train.value_counts(normalize=True)
prior_probabilities


Play
Yes    0.578947
No     0.421053
Name: proportion, dtype: float64

Kode ini menghitung probabilitas prior untuk setiap kelas pada data pelatihan y_train. Probabilitas prior menunjukkan seberapa besar proporsi masing-masing kelas dalam dataset sebelum melihat fitur-fiturnya.

Fungsi value_counts(normalize=True) digunakan untuk menghitung frekuensi masing-masing kelas, lalu mengubahnya menjadi proporsi relatif (dalam bentuk persentase atau desimal antara 0 dan 1) dari total data pelatihan.

Hasilnya disimpan dalam variabel prior_probabilities, yang dapat digunakan dalam model probabilistik seperti Naive Bayes untuk memperkirakan kemungkinan dasar dari setiap kelas sebelum memperhitungkan fitur-fitur lain. Nilai ini membantu model memahami distribusi kelas secara keseluruhan dalam data latih.

2.feature probability calculation

In [6]:
def calculate_feature_probabilities(X_train_transformed, y_train, feature_names):
    classes = y_train.unique()
    equations = pd.DataFrame(index=classes, columns=feature_names)

    for cls in classes:
      X_class = X_train_transformed[y_train == cls]
        mean = X_class.mean(axis=0)
        std = X_class.std(axis=0)
        k1 = 1 / (std * np.sqrt(2 * np.pi))
        k2 = 2 * (std ** 2)

        for i, column in enumerate(feature_names):
            equation = f"{k1[i]:.3f}.exp(-(x-({mean[i]:.2f}))"

IndentationError: unexpected indent (<ipython-input-6-1485757540>, line 7)

Fungsi calculate_feature_probabilities ini bertujuan menghitung persamaan probabilitas fitur berdasarkan data latih yang sudah ditransformasi (X_train_transformed) dan labelnya (y_train). Probabilitas ini biasanya digunakan dalam model Gaussian Naive Bayes, di mana setiap fitur dianggap berdistribusi normal dengan mean dan standar deviasi tertentu tergantung kelasnya.



classes = y_train.unique() digunakan untuk mendapatkan daftar kelas unik yang ada di data latih.

equations = pd.DataFrame(index=classes, columns=feature_names) membuat sebuah DataFrame kosong yang nanti akan diisi dengan rumus probabilitas untuk setiap fitur dan kelas.

Pada loop for cls in classes: dilakukan pemisahan data fitur hanya yang termasuk kelas tertentu (X_class).

Kemudian dihitung nilai rata-rata (mean) dan standar deviasi (std) untuk setiap fitur pada kelas tersebut.

k1 dan k2 adalah bagian dari rumus distribusi normal Gaussian, di mana k1 adalah konstanta pembagi dan k2 terkait dengan varians (kuadrat standar deviasi).

Dalam loop kedua, untuk setiap fitur di kelas tertentu, rumus probabilitas Gaussian dibentuk dalam bentuk string. Tapi di kode kamu rumusnya belum selesai.